spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Ravi@123
    url: jdbc:mysql://localhost:3306/Foodiyapa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
    
#debug: true